version: '3.8'

services:
  api:
    build:
      context: ./simple-api
      dockerfile: Dockerfile
    ports:
      - "5044:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - angular

  angular:
    build:
      context: ./simple-angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"